apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
  labels:
    component: elk
    app: logstash
spec:
  selector:
    component: elk
    app: logstash
  ports:
  - name: lumberjack
    port: 5043
    protocol: TCP
  - name: logspout
    port: 5000
    protocol: UDP
