apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  namespace: elk
  labels:
    component: elk
    role: logstash
spec:
  replicas: 1
  selector:
    component: elk
    role: logstash
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      serviceAccount: elk
      containers:
      - name: logstash
        image: infracloud/docker-logstash
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: ES_HOST_NAME
          value: http\:\/\/elasticsearch.elk.svc.cluster.local\:9200
        ports:
        - containerPort: 5043
          name: lumberjack
          protocol: TCP
        - containerPort: 5000
          name: logspout
          protocol: UDP
        volumeMounts:
        - mountPath: /certs
          name: certs
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
      - hostPath:
          path: "/tmp"
        name: "certs"