apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
  labels:
    component: elk
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elk
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        component: elk
        app: kibana
    spec:
      serviceAccount: elk
      containers:
      - name: kibana
        image: quay.io/pires/docker-kibana:4.1.1
        env:
        - name: KIBANA_ES_URL
          value: "http://elasticsearch.elk.svc.cluster.local:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        args:
{{ range $k, $v  := .Values.args }}
          - '-{{$k}}={{$v}}'
{{ end }}
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
