apiVersion: v1
kind: Service
metadata:
  name: prom-es-exporter
  namespace: elk
  labels: 
    component: elk
    app: prom-es-exporter
spec:
  type: NodePort
  selector:
    component: elk
    app: prom-es-exporter
  ports:
  - name: web
    port: 8080
    protocol: TCP
