apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-es-exporter
  namespace: elk
data:
  exporter.cfg: |-
    # Queries are defined in sections beginning with 'query_'.
    # Characters following this prefix will be used as a prefix for all metrics
    # generated for this query
    [query_all]
    # How often to run this query.
    QueryIntervalSecs = 5
    # The indices to run the query on. Any way of specifying indices supported by your Elasticsearch version can be used.
    # This key is optional - if not specified, the default is '_all'.
    QueryIndices = _all
    # The search query to run.
    QueryJson = {
        "size": 0,
        "query": {
            "match_all": {}
        }
    }

    [query_path]
    QueryIntervalSecs = 20
    QueryIndices = _all
    QueryJson = {
        "query": {
            "query_string": {
                "query": "path: \"/login\" AND remote_ip: \"172.17.0.1\""
            }
        }
    }
